# from https://stackoverflow.com/questions/51866926
# and https://github.com/jangorecki/r.gitlab.ci
image: rocker/r-base
gitlab:
   script:
    - apt-get update
    - apt-get install --yes libssl-dev libcurl4-openssl-dev libxml2-dev
    - R -e "install.packages(c('backports', 'curl', 'crayon', 'data', 'dplyr', 'hms', 'knitr', 'rlang', 'rvest', 'tidyr', 'xml2', 'covr', 'ggplot2', 'rmarkdown', 'rstudioapi', 'testthat'))"
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
