# ==================================================================== #
# TITLE                                                                #
# Antimicrobial Resistance (AMR) Analysis                              #
#                                                                      #
# SOURCE                                                               #
# https://gitlab.com/msberends/AMR                                     #
#                                                                      #
# LICENCE                                                              #
# (c) 2019 Berends MS (m.s.berends@umcg.nl), Luz CF (c.f.luz@umcg.nl)  #
#                                                                      #
# This R package is free software; you can freely use and distribute   #
# it for both personal and commercial purposes under the terms of the  #
# GNU General Public License version 2.0 (GNU GPL-2), as published by  #
# the Free Software Foundation.                                        #
#                                                                      #
# This R package was created for academic research and was publicly    #
# released in the hope that it will be useful, but it comes WITHOUT    #
# ANY WARRANTY OR LIABILITY.                                           #
# Visit our website for more info: https://msberends.gitab.io/AMR.     #
# ==================================================================== #

stages:
  - build
  - test
  - deploy

# debian stretch only contains R 3.3...
image: debian:buster-slim

before_script:
  - apt-get update -qq
  # install dependencies for packages
  - apt-get install -y wget locales libxml2-dev libssl-dev libcurl4-openssl-dev zlib1g-dev r-base > /dev/null
  # recent pandoc
  - wget --quiet https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb
  - dpkg -i pandoc*.deb
  - rm pandoc*.deb
  # set R system language
  - echo "LC_ALL=en_US.UTF-8" >> /etc/environment
  - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
  - echo "LANG=en_US.UTF-8" > /etc/locale.conf
  - locale-gen
  # cache R packages
  - mkdir -p installed_deps
  - echo 'R_LIBS="installed_deps"' > .Renviron
  - echo 'R_LIBS_USER="installed_deps"' >> .Renviron
  - echo 'R_LIBS_SITE="installed_deps"' >> .Renviron
  # set language
  - echo 'LANGUAGE="en_US.utf8"' >> .Renviron
  - echo 'LANG="en_US.utf8"' >> .Renviron
  - echo 'LANGUAGE="en_US.utf8"' > ~/.Renviron
  - Rscript -e 'sessionInfo()'
  # install missing and outdated packages
  - Rscript -e 'source(".gitlab-ci.R"); gl_update_pkg_all(repos = "https://cran.rstudio.com", quiet = TRUE, install_pkgdown = TRUE)'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - installed_deps/

R:
  stage: build
  allow_failure: false
  variables:
    WARNINGS_ARE_ERRORS: 1
  script:
    - export WARNINGS_ARE_ERRORS=1
    # remove vignettes folder and get VignetteBuilder field out of DESCRIPTION file
    - rm -rf vignettes
    - Rscript -e 'd <- read.dcf("DESCRIPTION"); d[, colnames(d) == "VignetteBuilder"] <- NA; write.dcf(d, "DESCRIPTION")'
    # build package
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  artifacts:
    paths:
      - '*.Rcheck/*'
    expire_in: '1 month'

coverage:
  stage: test
  allow_failure: true
  when: on_success
  only:
    - premaster
    - master
  script:
  - apt-get install --yes git
  - Rscript -e 'cc <- covr::package_coverage(); covr::codecov(coverage = cc, token = "50ffa0aa-fee0-4f8b-a11d-8c7edc6d32ca"); cat("Code coverage:", covr::percent_coverage(cc))'
  coverage: '/Code coverage: \d+\.\d+/'

pages:
  stage: deploy
  when: always
  only:
    - master
  script:
    #- Rscript -e "install.packages('pkgdown', repos = 'https://cran.rstudio.com')"
    - Rscript -e "devtools::install(build = TRUE, upgrade = FALSE)"
    - R -e "pkgdown::build_site(examples = FALSE, lazy = TRUE, override = list(destination = 'public'))"
  artifacts:
    paths:
      - public
