# Setting up R deps
language: r
r: 3.2
r_packages: covr
cache: packages

# system deps, install xclip for clipboard support
os:
  - linux
  - osx
before_install:
  # needed for clipboard function:
  # - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y xclip; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install xclip; fi

# postrun
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
      - m.s.berends@umcg.nl
      # - c.f.luz@umcg.nl
    on_success: change
    on_failure: change
