# Setting up R deps
language: r
jobs:
  include:
  - r: 3.1
    os:
    - linux
    - osx
    warnings_are_errors: false
  - r: 3.2
    os:
    - linux
    - osx
    warnings_are_errors: false
  - r: 3.3
    os:
    - linux
    - osx
  - r: 3.4
    os:
    - linux
    - osx
  - r: release
    os:
    - linux
    - osx
  - r: devel
    os:
    - linux
    - osx
    warnings_are_errors: false
r_packages: covr
cache: packages
cran: https://cran.rstudio.com
before_install:
  # needed for clipboard function:
  # - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y xclip; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install xclip; fi

# postrun
after_success:
  - Rscript -e 'covr::codecov()'
    if: os = osx
notifications:
  email:
    recipients:
      - m.s.berends@umcg.nl
      # - c.f.luz@umcg.nl
    on_success: change
    on_failure: change
