# Setting up R deps
language: R
dist: trusty
cache: packages

jobs:
  include:
  - r: 3.1
  - r: 3.2
  - r: 3.3
  - r: 3.4
  - r: release
  - r: devel
    warnings_are_errors: false

r_packages: covr
cache: packages
cran: https://cran.rstudio.com
os:
  - linux
  - osx
before_install:
  # needed for clipboard function:
  # - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y xclip; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install xclip; fi

# postrun
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
      - m.s.berends@umcg.nl
      # - c.f.luz@umcg.nl
    on_success: change
    on_failure: change
