# Setting up R deps
language: r
jobs:
  include:
  - r: 3.1
    os: linux
    warnings_are_errors: false
  - r: 3.2
    os: linux
  - r: 3.2
    os: osx
  - r: 3.3
    os: linux
  - r: 3.3
    os: osx
  - r: 3.4
    os: linux
  - r: 3.4
    os: osx
  - r: release
    os: linux
  - r: release
    os: osx
  - r: devel
    os: linux
    warnings_are_errors: false
matrix:
  allow_failures:
    - r: 3.2
      os: osx
    - r: 3.3
      os: osx
    - r: 3.4
      os: osx
r_packages: covr
cache: packages
cran: https://cran.rstudio.com

install:
  - Rscript -e "install.packages(c('devtools', 'backports', 'clipr', 'curl', 'data.table', 'dplyr', 'hms', 'knitr', 'readr', 'rlang', 'rvest', 'xml2', 'covr', 'ggplot2', 'rmarkdown', 'testthat', 'tidyr'))"
  - if [ $TRAVIS_OS_NAME = osx ]; then Rscript -e "devtools::install_github('r-lib/rlang')"; fi

# postrun
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    recipients:
      - m.s.berends@umcg.nl
      # - c.f.luz@umcg.nl
    on_success: change
    on_failure: change
