codecov:
  notify:
    require_ci_to_pass: no
  ci:
    - !appveyor # ignore CI builds by AppVeyor

comment: no

coverage:
  precision: 1
  round: up
  range: "0...100"
  status:
    project: no
    patch: no
    changes: no

ignore:
  - "R/atc_online.R"
  - "R/mo_source.R"
  - "R/resistance_predict.R"
